config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :buckets do
  	member do
  		put "like",    to: "buckets#upvote"
  	end
  end

  root "buckets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bucket.rb
class Bucket < ApplicationRecord
	acts_as_votable
	
	belongs_to :user

    has_attached_file :image, styles: { medium: "300x300>" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :buckets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/buckets_controller.rb
class BucketsController < ApplicationController

	before_action :find_bucket, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@buckets = Bucket.all.order("created_at DESC")
	end	

	def show
	end

	def new
		@bucket = current_user.buckets.build
	end

	def create
		@bucket = current_user.buckets.build(bucket_params)

		if @bucket.save
			redirect_to @bucket, notice: "Successfully created new Bucket"

		else
			render 'new'
		end
	end

	def update
		if @bucket.update(bucket_params)
			redirect_to @bucket, notice: "Bucket was Successfully updated!"

		else
			render 'edit'
		end
	end

	def destroy
		@bucket.destroy
		redirect_to root_path
	end

	def upvote
		@bucket.upvote_by current_user
		redirect_back fallback_location: root_path
	end

	def back
		
	end


	private

	def bucket_params
		params.require(:bucket).permit(:title, :description, :image)
	end

	def find_bucket
		@bucket = Bucket.find(params[:id])
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buckets_helper.rb
module BucketsHelper
end

app/views/buckets/_footer.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %meta{:content => "footer, address, phone, icons", :name => "keywords"}/
    %title
    %link{:href => "stylesheets/footer.scss", :rel => "stylesheet"}/
    %link{:href => "http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    %link{:href => "http://fonts.googleapis.com/css?family=Cookie", :rel => "stylesheet", :type => "text/css"}/
  %body
    / The content of your page would go here.
    %footer.footer-distributed
      .footer-left
        %p.footer-company-name Bucket List © 2018
      .footer-center
        %div
          %i.fa.fa-map-marker
          %p
            %span 18/F Tallabag
            Dhaka, Bangladesh
        %div
          %i.fa.fa-phone
          %p +88-01795-323956
        %div
          %i.fa.fa-envelope
          %p
            %a{:href => "mailto:support@company.com"} zahidcse4960@gmail.com
      .footer-right
        %p.footer-company-about
          %span About the Bucket List
          Lorem ipsum dolor sit amet, consectateur adispicing elit. Fusce euismod convallis velit, eu auctor lacus vehicula sit amet.
        .footer-icons
          %a{:href => "https://www.facebook.com/profile.php?id=100010866516396"}
            %i.fa.fa-facebook
          %a{:href => "https://twitter.com/ZahidHasan4960"}
            %i.fa.fa-twitter
          %a{:href => "https://www.linkedin.com/in/zahid-hasan-381aa1153/"}
            %i.fa.fa-linkedin
          %a{:href => "https://github.com/Zahid4960"}
            %i.fa.fa-github
%br/

app/views/buckets/_form.html.haml
= simple_form_for @bucket, html: { multipart: true } do |f|
  - if @bucket.errors.any? 
    #errors
      %h2
      = pluralize(@bucket.errors.count, "error") 
      prevented this bucket from saving
      %ul
        - @bucket.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.input :image, input_html: { class: 'form-control'}

  .form-group
    = f.input :title, input_html: { class: 'form-control'}	

  .form-group
    = f.input :description, input_html: { class: 'form-control'}

  = f.button :submit, class: 'btn btn-success' 			

app/views/buckets/edit.html.haml
.col-md-6.col-md-offset-3
  .row
    .panel.panel-default
      .panel-heading
        %h1 Edit Bucket
      .panel-body  
        %strong.center current Image
        %br/
        = image_tag @bucket.image.url(:medium)
        %br/
        = render 'form'

app/views/buckets/index.html.haml
#buckets.transitions-enabled
  - @buckets.each do |bucket|
    .box.panel.panel-default
      = link_to (image_tag bucket.image.url), bucket
      .panel-body
        %h2= link_to bucket.title, bucket
        %p.user
        Submitted by
        = bucket.user.email

= render 'footer'        

app/views/buckets/new.html.haml
.col-md-6.col-md-offset-3
  .row
    .panel.panel-default
      .panel-heading
        %h1 New Bucket
      .panel-body  
        = render 'form'

app/views/buckets/show.html.haml
#bucket_show.row
  .col-md-6.col-md-offset-3
    .panel.panel-default
      .panel-heading.bucket_image
        = image_tag @bucket.image.url
    .panel-body
      %h1= @bucket.title 
      %p.description= @bucket.description
    .panel-footer
      .row
        .col-md-6
          %p.user
          Submitted by
          = @bucket.user.email
        .col-md-6
          .btn-group.pull-right
            = link_to like_bucket_path, method: :put, class: "btn btn-default" do
              %span.glyphicon.glyphicon-heart
                = @bucket.get_upvotes.size
            - if current_user.id == @bucket.user_id 
              = link_to "Edit", edit_bucket_path, class: "btn btn-success"
              = link_to "Delete",  bucket_path, method: :delete, data: { confirm: "Are you sure you want to delete the bucket?" }, class: "btn btn-danger"

app/views/layouts/application.html.haml
!!!5
%html
%head
  %title Bucket List
  = csrf_meta_tags
  = csp_meta_tag
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand= link_to "Bucket List", root_path

      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "New Bucket", new_bucket_path
          %li= link_to "Account", edit_user_registration_path
          %li= link_to "Sign Out", destroy_user_session_path, method: :delete
      
      - else
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Sign Up", new_user_registration_path
          %li= link_to "Sign In", new_user_session_path
    
  .container
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert alert-info"
   
    = yield   